version: "2"
services:

#==== INSTANCE MARIADB SPECIFIQUE A RANCHER-SERVER ====
  mariadb:
    image: mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iop
      - MYSQL_USER=cattle
      - MYSQL_PASSWORD=cattle
      - MYSQL_DATABASE=rancherdb

#==== INTERFACE GRAPHIQUE POUR MARIADB ====
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8000:80"
    volumes:
      - phpmyadmin:/sessions
    depends_on:
      - mariadb:db

#==== RANCHER SERVER EN VERSION ENTREPRISE - UTILISE LA BASE RANCHER-MARIADB ===
#==== Volumes MYSQL uniquement pour éviter la création de volumes par docker car BDD externalisée ===
#==== Volumes cattle pour les données specifiques à rancher ≡
  rancher:
    image: rancher/server:v1.1.4
    restart: always
    expose:
      - "8080"
    volumes:
      - cattle:/var/lib/cattle
      - mysql:/var/lib/mysql
      - mysql-log:/var/log/mysql
      - ./ca.cert.pem:/ca.crt:ro
    depends_on:
      - mariadb
    environment:
      - CATTLE_DB_CATTLE_MYSQL_HOST=mariadb
      - CATTLE_DB_CATTLE_MYSQL_PORT=3306
      - CATTLE_DB_CATTLE_MYSQL_NAME=rancherdb
      - CATTLE_DB_CATTLE_USERNAME=cattle
      - CATTLE_DB_CATTLE_PASSWORD=cattle

  proxy:
    build: ./rancher-proxy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - rancher

#=== DETAIL DES VOLUMES ===
volumes:
  mariadb:
  phpmyadmin:
  cattle:
  mysql:
  mysql-log:
